### ISSUE TITLE
ObjectMapper 빈 등록 및 LocalDateTime 직렬화 문제 커스터마이징 방법 탐구

### ISSUE THREAD

**Issue by je-pa** [cchoijjinyoung/springboot-auto-configuration#1]
## 문제

Spring Boot 애플리케이션에서 `new ObjectMapper()`로 직접 빈을 등록할 경우 기본 설정이 적용되지 않아 LocalDateTime 직렬화등의 문제가 발생할 수 있습니다.
 
## 해결 방안
아래 세 가지 방법으로 문제를 해결할 예정입니다:

- LocalDateTime 설정을 포함한 ObjectMapper 빈 직접 등록.
- Jackson2ObjectMapperBuilderCustomizer를 사용하여 LocalDateTime 직렬화만 설정.
- Jackson2ObjectMapperBuilder를 사용하여 LocalDateTime 직렬화만 설정.

## 학습 목표
- 기본 ObjectMapper 빈 등록 방식의 문제점을 확인.
- 이를 해결하기 위한 다양한 ObjectMapper 커스터마이징 방법을 학습.
  - Spring Boot에서 자동 등록된 ObjectMapper 빈을 커스터마이징할 때 전체를 재정의하지 않고, 필요한 부분만 조정할 수 있음을 이해.
  - 다양한 방법으로 ObjectMapper 빈을 커스터마이징하는 실습을 통해 적절한 전략을 선택하는 기준을 습득.

**Comment by cchoijjinyoung** [comment]
이슈 작성 고생하셨습니다! 감사합니다!

추가적인 부분을 더 작성해보자면, 스프링부트에서 ObjectMapper를 빈으로 등록할시에,
```java
@Bean
@Primary
@ConditionalOnMissingBean
ObjectMapper jacksonObjectMapper(Jackson2ObjectMapperBuilder builder) {
  return builder.createXmlMapper(false).build();
}
```
위 코드와 같이 등록되며, `Jackson2ObjectMapperBuilder`를 주입받는 것을 확인할 수 있습니다.
또한, 주입하는`Jackson2ObjectMapperBuilder`도 마찬가지로 아래 코드처럼 스프링부트가 자동으로 빈으로 등록해주는데요.
```java
@Bean
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
@ConditionalOnMissingBean
Jackson2ObjectMapperBuilder jacksonObjectMapperBuilder(ApplicationContext applicationContext,
		List<Jackson2ObjectMapperBuilderCustomizer> customizers) {
  Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
  builder.applicationContext(applicationContext);
  customize(builder, customizers);
  return builder;
}
```

위 코드를 살펴보면, `List<Jackson2ObjectMapperBuilderCustomizer> customizer`를 주입받아서 빌더를 커스텀해주는 것을 확인할 수 있습니다.

그런데, 우리가 `ObjectMapper`를 커스텀해주는 세가지 방법 중 하나인 `Customizer`를 빈으로 등록해주는 방법은, 우리가 빈으로 등록한 `Jackson2~Customizer`가  `List<Jackson2~Customizer>` 에 주입되게 되고, 스프링 부트는 내부적으로 customizers를 순회하여 `ObjectMapperBuilder`를 생성하게 됩니다.

그랬을 때, 아래와 같은 궁금한 점이 생겼습니다. 
- `Jackson2~Customzer`의 빈을 여러개 생성한다면 `List`에 여러 `Customizer`가 존재할텐데, 설정이 덮어씌워지는 것 일까? 
- 만약 덮어씌워진다면, 어떤 순서로 덮어씌워질까?

어쩌면 당연할지도 모르겠지만, 결과는 '마지막에 빈으로 등록된 `Customizer`의 설정으로 덮어씌워진다' 입니다. (중복된 설정에 한해서)

> [참고]
테스트 방법은 `Customizer`를 빈으로 등록할 때, `toString()`도 재정의해주었고, `List<Customizer>`를 순회해서 모든`Customizer`에 대해 `toString()`이 빈으로 등록된 순으로 출력되는지 확인하였습니다. 또한 설정도 순서대로 덮어씌워지는 지를 확인하였습니다.

수고하셨습니다! 😊
