### ISSUE TITLE
RestTemplate와 RestClient를 활용한 Trace ID 관리 및 비교 학습

### ISSUE THREAD

**Issue by je-pa** [cchoijjinyoung/springboot-auto-configuration#2]
## 배경

설정에 따라 RestTemplate을 이용하여 하나의 API에서 다른 API로 Rest 요청을 보내는 경우, 트레이스 관련 라이브러리를 적용했음에도 불구하고 로그 상의 Trace ID가 다르게 나타나는 문제가 발생할 수 있습니다. 동일한 API 호출 흐름 내에서 동일한 Trace ID를 유지해야 추적이 용이하며, Trace ID가 다를 경우 요청 간의 관계 파악이 어려워질 수 있기 때문에 이를 해결하고자 관련 설정을 알아보고자 합니다.

## 문제

- RestTemplate을 사용한 요청 간 Trace ID가 일관되지 않아 추적에 문제가 발생.
- 하나의 API 호출 흐름에서 동일한 Trace ID를 유지할 방법 필요.

## 해결 방안

1. RestTemplate 등록 시 ObservationConvention 및 ObservationRegistry 설정
    - RestTemplate을 Bean으로 등록하면서 ObservationConvention과 ObservationRegistry를 설정하여 Trace ID를 일관되게 유지.
2. RestTemplateBuilder를 활용한 RestTemplate 등록
    - RestTemplateBuilder를 주입받아 RestTemplate을 등록하여 Trace ID를 관리.
3. Spring 3.2 이상에서 RestClient 활용
    - RestTemplate 대신 Spring 3.2 이상에서 추천되는 RestClient를 사용하여 비교
      - 직접 생성한 RestClient를 빈으로 등록하여 비교
      - RestClient.Builder를 활용하여 빈 등록 후 비교

## 학습 목표

- Trace ID를 일관되게 유지하기 위한 설정 및 활용법 습득.

## 추가 라이브러리 

- 트레이싱 라이브러리 micrometer-tracing-bridge-otel

**Comment by cchoijjinyoung** [comment]
이슈 작성 감사합니다. 이번 내용을 학습하면서 배운점을 간략하게 적어보겠습니다.

1. Trace ID를 통해, 분산 환경에서 사용자의 요청에 대해 전체적인 흐름을 추적할 수 있다.
2. 스프링 부트에서 자동으로 빈으로 등록해주는 `RestTemplateBuilder`는 이미 하나의 요청에 대해 Trace ID가 일관되게 유지되도록 설정이 되어있다.
3. 우리가 직접 `RestTemplate`를 빈으로 등록하기 위해 `new RestTemplate`를 한다면, 이번 설정을 포함한 기본 설정을 일일히 직접 세팅해줘야하는 번거로움이 존재한다.
    - 일반적인 상황에서는 거의 `RestTemplateBuilder`(스프링 부트 3.2 이상부터는 `RestClient.Builder`)를 주입받아 커스텀해주는 것이 좋을 것 같다.

추후에 MSA 토이 프로젝트를 한다면, 이번 학습내용을 활용해볼 수 있을 것 같다는 생각이 드네요.

수고하셨습니다! 😊
