### ISSUE TITLE
MDC 전파 예시를 통한 ThreadPoolTaskExecutor 설정 방안 학습

### ISSUE THREAD

**Issue by cchoijjinyoung** [cchoijjinyoung/springboot-auto-configuration#3]
## 배경
비동기 작업을 처리하기 위해 `ThreadPoolTaskExecutor`를 사용할 수 있습니다. 이때, MDC (Mapped Diagnostic Context) 정보를 비동기 작업에서도 전파해야 할 경우가 있습니다. 이를 해결하기 위해 다양한 방법으로 `ThreadPoolTaskExecutor`를 설정하는 방안을 검토하려고 합니다.

## 해결 방안
1. `ThreadPoolTaskExecutor`를 직접 생성 및 설정 후 빈으로 등록
2. `TaskExecutorBuilder`를 주입받아 빈으로 등록
    - 스프링 부트의 기본 설정을 활용하며 decorator 설정만을 커스터마이징
3. `TaskDecorator`를 빈으로 등록하여 `TaskExecutorBuilder`에 적용
    - 스프링 부트에서 Builder를 빈으로 등록할 때, 사용될 수 있도록 별도의 Decorator만 빈으로 등록

## 학습 목표
- `ThreadPoolTaskExecutor` 설정의 유연성과 확장성 학습
- MDC(Mapped Diagostic Context) 이해
- 스프링 부트의 Auto-configuration 이해

**Comment by je-pa** [comment]
안녕하세요. 결과 작성하겠습니다!

먼저 해결 방안의 결과에 대해 작성하겠습니다.

## 해결 방법 결과

1. `ThreadPoolTaskExecutor`를 직접 생성 및 설정 후 빈으로 등록
    - `ThreadPoolTaskExecutor`를 직접 생성 및 설정 후 빈으로 등록했습니다.
       ```java
       /**
       * 결과: ThreadNamePrefix등의 설정이 가능
       */
       @Bean
      public ThreadPoolTaskExecutor threadPoolTaskExecutor(){
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setThreadNamePrefix("myThread-");
        return executor;
      }
       ```
    - 추가로 application.yml을 이용해서도 해당 설정을 변경할 수 있음을 확인했습니다.
       ```yaml
        spring:
          application:
            name: springboot-auto-configuration
          task:
            execution:
              thread-name-prefix: myTask- # Bean 등록으로 설정을 바꾸는 것이 아닌, application 설정만 추가해주면 된다.
       ```
  
    1의 실행 결과 콘솔은 아래와 같습니다.
      
      ![image](https://github.com/user-attachments/assets/34f2be09-c7cc-4e50-8a1c-a3d39551e98e)
    
    여기서 MDC(스레드별 정보)를 사용했을 때 추가로 실행한 비동기 스레드에서는 이전의 MDC정보를 읽을 수 없는 문제가 있었습니다.
    
    ![image](https://github.com/user-attachments/assets/75135ff3-c8d5-4b0a-9968-7ff95f78d7d7)
    
    해당 문제는 `TaskDecorator`를 교체해주면 해결이 가능합니다.

2. `TaskExecutorBuilder`를 주입받아 빈으로 등록
    - 스프링 부트의 기본 설정을 활용하며 decorator 설정만을 커스터마이징
        ```java
        /**
         * 2-2-1. ThreadPoolTaskExecutor를 빈으로 등록하며 설정을 변경해보자.
         * 결과: decorator를 설정함으로써 호출된 비동기 스레드가 MDC 정보를 이어서 받을 수 있다.
         */
        @Bean
        public ThreadPoolTaskExecutor threadPoolTaskExecutor(ThreadPoolTaskExecutorBuilder builder){
          return builder.threadNamePrefix("myThread!-").taskDecorator(new ThreadLocalCopyTaskDecorator()).build();
        }
        
        ```
    - 참고로 `ThreadPoolTaskExecutor`를 직접 생성하여 빈으로 등록하는 과정에서 `TaskDecorator`를 교체할 수 있습니다.
        ```java
        /**
         * 결과: decorator를 설정함으로써 호출된 비동기 스레드가 MDC 정보를 이어서 받을 수 있다.
         */
        @Bean
        public ThreadPoolTaskExecutor threadPoolTaskExecutor(){
          ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
          executor.setThreadNamePrefix("myThread!-");
          executor.setTaskDecorator(new ThreadLocalCopyTaskDecorator());
          return executor;
        }
        ```
       다만, 해당 방법은 `ThreadPoolTaskExecutor`의 일부분이 아닌 전체를 커스터마이징 하는 것이기 때문에 크게 필요치 않다면 위의 방법을 사용하는 것이 더 좋을 것 같습니다! 

3. `TaskDecorator`를 빈으로 등록하여 `TaskExecutorBuilder`에 적용
    - 스프링 부트에서 Builder를 빈으로 등록할 때, 사용될 수 있도록 별도의 Decorator만 빈으로 등록
      ```java
      /**
       * 결과: application.yml 설정을 적극 활용 가능하면서 TaskDecorator 같은 부품도 교체가 가능하다.
       */
      @Bean
      public TaskDecorator myTestDecorator(){
        return new ThreadLocalCopyTaskDecorator();
      }
      ```

   2, 3의 실행 결과 아래와 같습니다.

   ![image](https://github.com/user-attachments/assets/b501ad54-2124-4335-8dc1-87da2a02d054)

## 추가
- 스프링 부트의 SimpleAsyncTaskExecutorBuilderConfiguration.ThreadPoolTaskExecutorBuilderConfiguration에서 ThreadPoolTaskExecutorBuilder를 등록해주는 것을 확인할 수 있습니다.
    ```java
    @Bean
    @ConditionalOnMissingBean
    ThreadPoolTaskExecutorBuilder threadPoolTaskExecutorBuilder(TaskExecutionProperties properties, ObjectProvider<ThreadPoolTaskExecutorCustomizer> threadPoolTaskExecutorCustomizers, ObjectProvider<TaskDecorator> taskDecorator) {
      TaskExecutionProperties.Pool pool = properties.getPool();
      ThreadPoolTaskExecutorBuilder builder = new ThreadPoolTaskExecutorBuilder();
      builder = builder.queueCapacity(pool.getQueueCapacity());
      builder = builder.corePoolSize(pool.getCoreSize());
      builder = builder.maxPoolSize(pool.getMaxSize());
      builder = builder.allowCoreThreadTimeOut(pool.isAllowCoreThreadTimeout());
      builder = builder.keepAlive(pool.getKeepAlive());
      builder = builder.acceptTasksAfterContextClose(pool.getShutdown().isAcceptTasksAfterContextClose());
      TaskExecutionProperties.Shutdown shutdown = properties.getShutdown();
      builder = builder.awaitTermination(shutdown.isAwaitTermination());
      builder = builder.awaitTerminationPeriod(shutdown.getAwaitTerminationPeriod());
      builder = builder.threadNamePrefix(properties.getThreadNamePrefix());
      Stream var10001 = threadPoolTaskExecutorCustomizers.orderedStream();
      Objects.requireNonNull(var10001);
      builder = builder.customizers(var10001::iterator);
      builder = builder.taskDecorator((TaskDecorator)taskDecorator.getIfUnique());
      return builder;
    }
    ```
- 그리고 SimpleAsyncTaskExecutorBuilderConfiguration 에서 ThreadPoolTaskExecutorBuilder를 사용하여 ThreadPoolTaskExecutor를 등록해주는 것을 확인할 수 있습니다.
    ```java
    @Lazy
    @Bean(
      name = {"applicationTaskExecutor", "taskExecutor"}
    )
    @ConditionalOnThreading(Threading.PLATFORM)
    ThreadPoolTaskExecutor applicationTaskExecutor(ThreadPoolTaskExecutorBuilder threadPoolTaskExecutorBuilder) {
      return threadPoolTaskExecutorBuilder.build();
    }
    ```
감사합니다!
